{
    "version": 1,
    "debug": 1,
    "uid": "3ac516xx",
    "place": "test",
    "timeinterval": 10,
    "rundemo": 0,
    "tempoffset": -1,
    "mtemp": 1,
    "mlight": 1,
    "mmoist": 1,
    "manalog": 0,
    "manlight": 0,
    "mantemp": 0,
    "mlight2": 0,
    "startlight": 11,
    "stoplight": 12,
    "lightintensity": 500,
    "pumpnodes": [ 9, 19 ],
    "pumpduration": 1,
    "uid8": 1,
    "cloudconfig": 1,
    "cloudconfdynam": 1,
    "cloudupdate": 0
}
